title: <p align="center"> Yeshwanth Rajaram </p>
logo: /assets/img/yr.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/yeshwanth-rajaram">LinkedIn</a> |
  <a href="https://github.com/yeshwanthbr">GitHub</a>
 
  <br>  
  Lead Developer at SAP Labs. 
  Data Science and Artificial Intelligence enthusiast.
  <br>
  </p>
